import {request as staticRequest} from './static_api.js';
import {mountSeasonInsights} from './season_insights.js';
import {renderTeamProfile,teamHref,archiveHref} from './team_profiles.js';
import {mountMatchupComparison} from './matchup_compare.js';
const main=document.querySelector('main'),dialog=document.querySelector('#detail');
const $=s=>document.querySelector(s);
// Moving to content must not enter the hash router.
$('.skip').addEventListener('click',event=>{
  event.preventDefault();
  main.focus({preventScroll:true});
  main.scrollIntoView({block:'start'});
});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=p=>p==null?'—':`${(p*100).toFixed(1)}%`,num=(n,d=4)=>n==null?'—':Number(n).toFixed(d);
let summary,season,region=0,year=2026,simulation=null,view='actual',routeVersion=0,seasonRequest=0;
const simulations=new Map();
async function api(path,options){if(document.querySelector('meta[name="march-mode"]')?.content==='static')return staticRequest(path,options);const r=await fetch(path,options),data=await r.json();if(!r.ok)throw Error(data.error||`Request failed (${r.status})`);return data;}
function error(e,target=main){target.innerHTML=`<div class="error" role="alert">${esc(e.message)} <button id="retry">Try again</button></div>`;$('#retry')?.addEventListener('click',renderRoute);}
function heading(eye,title,note=''){return `<p class="eyebrow">${eye}</p><h1>${title}</h1>${note?`<p class="muted">${note}</p>`:''}`;}
function stat(v,n){return `<div class="stat"><strong>${v}</strong><span>${n}</span></div>`;}
function upcoming(){
main.innerHTML=heading('THE NEXT TOURNAMENT','March 2027','Men’s Division I · Selection Sunday March 14 · Detroit Final Four')+
`<section class="hero"><div><span class="tag">FIELD NOT ANNOUNCED</span><h2 style="margin-top:20px">The road to Detroit starts here.</h2><p class="muted">The 2027 bracket will have 76 teams. Team predictions become available when the actual field, seeds and opening-game placements are announced.</p><a class="button primary" href="#archive">Explore the historical bracket</a> <a class="button" href="#matchup">Try a seed matchup</a></div><div class="hero-side"><div class="hero-number">76</div><small>TEAMS<br>12 OPENING GAMES<br>ONE CHAMPION</small></div></section>
<div class="stats">${stat(41,'Archived main brackets · 1985–2026')}${stat('2,582','Played games · one no-contest excluded')}${stat('2026','Latest completed tournament')}${stat('377','Chronological holdout games · 2021–2026')}</div>
<section class="panel"><h2>Tournament calendar</h2><div class="schedule"><div><strong>March 14</strong><span>Selection Sunday</span></div><div><strong>March 16–17</strong><span>Opening Round · 12 games</span></div><div><strong>April 3 & 5</strong><span>Final Four & championship · Detroit</span></div></div><p class="note" style="margin-top:20px"><a href="${esc(summary.field.source)}" target="_blank" rel="noreferrer">Official NCAA schedule</a> · checked October 3, 2026. Field assignments remain unknown.</p></section>
<div class="panels"><section class="panel"><h2>A model with a visible record</h2><p class="muted">The primary seed model scored ${num(summary.evaluation.holdout_metrics.seed.brier)} Brier on 377 held-out games. Lower is better. Compare the challengers and calibration before using a probability.</p><a href="#evidence">Read the evaluation →</a></section><section class="panel"><h2>Bring the announced bracket</h2><p class="muted">Import a JSON field with 64 ordered slots, including 12 opening-game pairs. The local app validates the structure and calculates advancement odds.</p><label for="field-file">Import field JSON<input type="file" id="field-file" accept="application/json,.json"></label><div id="import-status" class="statusline" role="status"></div><details><summary>Field format</summary><p class="note">Four regions in semifinal pairing order. Each region’s seeds: 1,16,8,9,4,13,5,12,2,15,7,10,3,14,6,11. A slot is one team, or two teams sharing that slot’s seed.</p><pre>{ "season": 2027, "status": "announced", "expected_teams": 76, "expected_opening_games": 12, "slots": [ [{"id":"actual-team-id","name":"Actual team","seed":1}], ... ] }</pre><p class="note">The example shows the schema only. Supply every real team and slot from the announced bracket.</p></details></section></div><section id="import-result"></section>`;
$('#field-file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;const status=$('#import-status');status.textContent='Validating field…';try{if(f.size>100000)throw Error('Choose a JSON file under 100 KB.');const field=JSON.parse(await f.text());const r=await api('/api/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({field})});status.textContent=`Validated ${r.participants} teams and ${r.total_games} games.`;drawImported(field,r);}catch(err){status.innerHTML=`<span class="error" role="alert">${esc(err.message)}</span>`;}});
}
function drawImported(field,result,index=0){
  const context={teams:field.slots.flat(),features:{},model:summary.models.models.seed};
  const groups=result.sampled_rounds.filter((r,i)=>index===4?i>=4:i<4).map((r,i)=>({round_name:r.round_name,games:index===4?r.games:r.games.slice(index*r.games.length/4,(index+1)*r.games.length/4)}));
  $('#import-result').innerHTML=`<section class="panel"><h2>Imported ${field.season} bracket</h2><p class="note">One seeded simulated draw. Open any matchup for the seed-model probability. This field was supplied locally and has not been verified against the NCAA announcement.</p><div class="segmented">${[0,1,2,3,4].map(i=>`<button data-import-region="${i}" aria-pressed="${i===index}">${i===4?'Final Four':`Region ${i+1}`}</button>`).join('')}</div>${result.sampled_opening.length?`<details><summary>Opening-game draw · ${result.opening_games} games</summary><div class="table-scroll"><table><thead><tr><th>Matchup</th><th>Draw winner</th><th class="numeric">Top team chance</th></tr></thead><tbody>${result.sampled_opening.map(g=>`<tr><td>${esc(g.a)} vs ${esc(g.b)}</td><td>${esc(g.winner)}</td><td class="numeric">${pct(g.p_a)}</td></tr>`).join('')}</tbody></table></div></details>`:''}<label class="mobile-round" for="import-round">Round<select id="import-round">${groups.map((g,i)=>`<option value="${i}">${esc(g.round_name)}</option>`).join('')}</select></label>${bracketMarkup(groups,index===4?2:8,context.teams)}<h3>Advancement odds · all possible paths</h3>${oddsTable(result.odds)}<p class="note">Seed model fitted through 2026. ${esc(result.caveat)}</p></section>`;
  document.querySelectorAll('[data-import-region]').forEach(b=>b.onclick=()=>drawImported(field,result,+b.dataset.importRegion));
  $('#import-round').onchange=e=>document.querySelectorAll('#import-result .round-column').forEach((col,i)=>col.classList.toggle('mobile-selected',i===+e.target.value));
  $('#import-result').querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>{const [col,j]=b.dataset.game.split('-').map(Number),g=groups[col].games[j];showGame({...g,seed_a:context.teams.find(t=>t.id===g.a).seed,seed_b:context.teams.find(t=>t.id===g.b).seed,round_name:groups[col].round_name},context,field.season,'sample');});
}
function syncArchiveRoute(game=null){history.replaceState(null,'',archiveHref({year,region,view,game}));}
async function archive({focusGame=null}={}){
main.innerHTML=heading('REAL TOURNAMENT HISTORY','Historical bracket','Choose a year and region. Open a game for probabilities and comparison, then select a team name to explore its recorded tournament history.')+
`<div class="toolbar"><label for="archive-year">Tournament year<select id="archive-year">${summary.years.map(y=>`<option ${y===year?'selected':''}>${y}</option>`).join('')}</select></label><div class="grow"></div><button id="draw-bracket">Simulate this field</button></div><div id="season-content" role="status" class="loading">Loading ${year} bracket…</div>`;
$('#archive-year').addEventListener('change',e=>{year=Number(e.target.value);region=0;simulation=simulations.get(year)||null;view='actual';syncArchiveRoute();archive();});
$('#draw-bracket').addEventListener('click',async()=>{
  const btn=$('#draw-bracket'),version=routeVersion,request=seasonRequest,selectedYear=year;
  const isCurrent=()=>version===routeVersion&&request===seasonRequest&&selectedYear===year&&btn.isConnected;
  btn.disabled=true;btn.textContent='Calculating…';
  try{
    const loaded=await api(`/api/simulate?year=${selectedYear}&rng=${Date.now()%1000000}`);
    if(!isCurrent())return;
    simulation=loaded;simulations.set(selectedYear,loaded);view='sample';syncArchiveRoute();drawArchive();
  }catch(e){if(isCurrent())error(e,$('#season-content'));}
  finally{if(isCurrent()){btn.disabled=false;btn.textContent='Draw another bracket';}}
});
const version=routeVersion,request=++seasonRequest;try{const loaded=await api(`/api/season?year=${year}`);if(version!==routeVersion||request!==seasonRequest)return;season=loaded;$('#draw-bracket').disabled=!season.model;drawArchive();if(focusGame){const card=[...main.querySelectorAll('[data-game]')].find(b=>b.dataset.game===focusGame);if(card){const column=card.closest('.round-column');main.querySelectorAll('.round-column').forEach(col=>col.classList.toggle('mobile-selected',col===column));$('#mobile-round').value=column.dataset.column;card.focus();}}}catch(e){if(version===routeVersion&&request===seasonRequest)error(e,$('#season-content'));}
}
function labelTeam(id){return season?.teams.find(t=>t.id===id)?.name||id;}
function bracketMarkup(groups,count,teams=season.teams){
  const height=count*78,teamName=id=>teams.find(t=>t.id===id)?.name||id;
  return `<div class="bracket-scroll" tabindex="0" aria-label="Tournament bracket, scroll horizontally to see later rounds"><div class="bracket">${groups.map((round,col)=>{
    const block=height/round.games.length;
    const cards=round.games.map((g,j)=>`<button class="game" data-game="${esc(g.id||`${col}-${j}`)}" style="top:${(j+.5)*block-31.5}px" aria-label="${esc(teamName(g.a))} versus ${esc(teamName(g.b))}, ${esc(round.round_name)}, open details"><span class="team-line ${g.winner===g.a?'won':'lost'}"><span class="seed">${g.seed_a||teams.find(t=>t.id===g.a)?.seed}</span><span class="team-name">${esc(teamName(g.a))}</span><span class="game-prob">${g.status==='no_contest'?'NC':pct(g.p_a)}</span></span><span class="team-line ${g.winner===g.b?'won':'lost'}"><span class="seed">${g.seed_b||teams.find(t=>t.id===g.b)?.seed}</span><span class="team-name">${esc(teamName(g.b))}</span></span></button>`).join('');
    let connectors='';
    if(col<groups.length-1){for(let j=0;j<round.games.length/2;j++){const y1=(j*2+.5)*block,y2=(j*2+1.5)*block,ym=(y1+y2)/2;connectors+=`<path d="M0 ${y1} H14 V${y2} H0 M14 ${ym} H28"/>`;}}
    return `<section class="round-column ${col===0?'mobile-selected':''}" data-column="${col}"><h3 class="round-label">${esc(round.round_name)}</h3><div class="round-games" style="height:${height}px">${cards}${connectors?`<svg class="connectors" width="28" height="${height}" viewBox="0 0 28 ${height}" aria-hidden="true">${connectors}</svg>`:''}</div></section>`;
  }).join('')}</div></div>`;
}
function drawArchive(){const played=season.games.filter(g=>g.status==='played').length,groups=[];
for(let r=1;r<=6;r++){let games=view==='sample'?simulation.sampled_rounds[r-1].games:season.games.filter(g=>g.round===r);if(region===4&&r>=5)groups.push({round_name:['Final Four','Championship'][r-5],games});if(region<4&&r<=4){const perRegion=games.length/4;groups.push({round_name:['Round of 64','Round of 32','Sweet 16','Elite Eight'][r-1],games:games.slice(region*perRegion,(region+1)*perRegion)});}}
$('#season-content').className='';$('#season-content').removeAttribute('role');
$('#season-content').innerHTML=`<div class="stats">${stat(esc(season.champion),'Actual champion')}${stat(played,'Played main-bracket games')}${stat(season.model?maxTrain(season.model):'—','Model trained through')}${stat(Object.keys(season.features).length,'Teams with pre-March form features')}</div>
<div class="segmented" aria-label="Bracket region">${[0,1,2,3,4].map(r=>`<button data-region="${r}" aria-pressed="${r===region}">${r===4?'Final Four':`Region ${r+1}`}</button>`).join('')}</div>
${simulation?`<div class="segmented" aria-label="Actual or simulated results"><button data-view="actual" aria-pressed="${view==='actual'}">Actual results</button><button data-view="sample" aria-pressed="${view==='sample'}">Simulated draw</button></div>`:''}
<p class="bracket-key">${view==='actual'?'✓ Actual winner · blue % is the historical model’s chance for the top team':'✓ Winner in one simulated draw · probabilities use the historical model'} · ${season.model?'trained on prior tournaments':'probabilities unavailable during 1985–1994 warm-up'}</p><label class="mobile-round" for="mobile-round">Round<select id="mobile-round">${groups.map((g,i)=>`<option value="${i}">${esc(g.round_name)}</option>`).join('')}</select></label>${bracketMarkup(groups,region===4?2:8)}
<p class="note">Region numbers preserve the source’s bracket order; geographic names are unavailable. ${season.games.some(g=>g.score_a!=null)?'Verified scores and UTC dates appear in game details.':'Scores and dates are missing for this era.'} Preliminary-round games and losers are excluded.${year===2021?' Oregon–VCU was a no-contest; the advancement is shown and excluded from model fitting.':''}</p>
${simulation?`<section class="panel"><h2>Advancement probabilities · ${year}</h2><p class="note">Exact probabilities across all possible main-bracket paths. Conditional on the 64 main-bracket participants; this is a historical experiment. ${view==='sample'?'The draw above is one sample.':'The bracket above shows recorded actual results.'}</p>${oddsTable(simulation.odds)}<p class="note">${esc(simulation.caveat)}</p></section>`:''}
<details><summary>Archive coverage and missing years</summary><p class="note">41 main brackets, 1985–2026. The 2020 tournament was cancelled. The 1939–1984 archive has not been ingested. Earlier history and modern feature coverage are separate.</p><div class="year-grid">${summary.years.map(y=>`<button data-year="${y}" aria-label="Open ${y} tournament">${y}</button>`).join('')}</div></details>`;
document.querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>{region=+b.dataset.region;syncArchiveRoute();drawArchive();});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;syncArchiveRoute();drawArchive();});document.querySelectorAll('[data-year]').forEach(b=>b.onclick=()=>{year=+b.dataset.year;region=0;simulation=simulations.get(year)||null;view='actual';syncArchiveRoute();archive();});
$('#mobile-round').addEventListener('change',e=>document.querySelectorAll('#season-content .round-column').forEach((col,i)=>col.classList.toggle('mobile-selected',i===+e.target.value)));
document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>{const idx=b.dataset.game;let g;if(view==='actual')g=season.games.find(g=>g.id===idx);else{const [col,j]=idx.split('-').map(Number);g=groups[col].games[j];g={...g,seed_a:season.teams.find(t=>t.id===g.a).seed,seed_b:season.teams.find(t=>t.id===g.b).seed,round_name:groups[col].round_name};}syncArchiveRoute(idx);showGame(g,season,year,view,{year,region,game:idx,view});});
}
const maxTrain=m=>Math.max(...m.train_seasons);
function oddsTable(odds){return `<div class="table-scroll"><table><caption class="sr-only">Team advancement probabilities</caption><thead><tr><th>Team</th><th>Seed</th><th class="numeric">Sweet 16</th><th class="numeric">Final Four</th><th class="numeric">Final</th><th class="numeric">Champion</th></tr></thead><tbody>${odds.map(t=>`<tr><td>${esc(t.name)}</td><td>${t.seed}</td><td class="numeric">${pct(t.reach_sweet16)}</td><td class="numeric">${pct(t.reach_final4)}</td><td class="numeric">${pct(t.reach_final)}</td><td class="numeric best">${pct(t.champion)}</td></tr>`).join('')}</tbody></table></div>`;}
const teamCell=(f,key,d=1)=>f?num(f[key],d):'—';
async function showGame(g,selectedSeason=season,selectedYear=year,selectedView=view,origin=null){const season=selectedSeason,year=selectedYear,view=selectedView,labelTeam=id=>season.teams.find(t=>t.id===id)?.name||id,fa=season.features[g.a],fb=season.features[g.b];
const linkedTeam=id=>{const team=season.teams.find(t=>t.id===id);return team?.profile_id&&origin?`<a href="${esc(teamHref(team.profile_id,origin))}" title="Explore ${esc(team.name)} tournament history">${esc(team.name)}</a>`:esc(labelTeam(id));};
$('#detail-body').innerHTML=`<p class="eyebrow">${year} · ${esc(g.round_name||'Bracket matchup')}</p><h2 class="detail-title" id="detail-title">${linkedTeam(g.a)} vs ${linkedTeam(g.b)}</h2>${origin?'<p class="note">Select a team name for its recorded tournament appearances.</p>':''}<p class="tag">${view==='sample'?'SIMULATED DRAW':g.status==='no_contest'?'NO CONTEST':'HISTORICAL RESULT'}</p>
<div class="comparison"><div><p class="muted">${esc(labelTeam(g.a))} · seed ${g.seed_a}</p><div class="probability">${pct(g.p_a)}</div></div><div class="right"><p class="muted">${esc(labelTeam(g.b))} · seed ${g.seed_b}</p><div class="probability">${g.p_a==null?'—':pct(1-g.p_a)}</div></div></div>
<p class="note">${season.model?`Seed model fitted through ${maxTrain(season.model)}. ${year===2027?'Scenario probability for a locally imported field.':'Seeds were known at selection; this is a retrospective probability. Later-round matchup identities became known as the tournament progressed.'}`:'No prediction snapshot: this tournament is within the model’s warm-up era.'}</p><p>${view==='sample'?'Draw winner':'Advancing team'}: <strong>${esc(labelTeam(g.winner))}</strong>${g.status==='no_contest'?' · game not played':''}</p>${view==='actual'?`<p class="note">${g.score_a==null?'Score unavailable':`Final: ${esc(labelTeam(g.a))} ${g.score_a} – ${g.score_b} ${esc(labelTeam(g.b))}`} · ${g.date_utc?esc(g.date_utc)+' (UTC)':'Date unavailable'}${g.result_source?' · verified against SportsDataverse/ESPN':''}</p>`:''}
<div class="table-scroll"><table><caption>Team comparison · form frozen March 1, 00:00 UTC</caption><thead><tr><th>Feature</th><th>${esc(labelTeam(g.a))}</th><th>${esc(labelTeam(g.b))}</th></tr></thead><tbody><tr><td>Seed</td><td>${g.seed_a}</td><td>${g.seed_b}</td></tr><tr><td>Within-season Elo</td><td>${teamCell(fa,'elo')}</td><td>${teamCell(fb,'elo')}</td></tr><tr><td>Win rate</td><td>${fa?pct(fa.win_rate):'—'}</td><td>${fb?pct(fb.win_rate):'—'}</td></tr><tr><td>Mean scoring margin</td><td>${teamCell(fa,'margin')}</td><td>${teamCell(fb,'margin')}</td></tr><tr><td>Completed games</td><td>${teamCell(fa,'games',0)}</td><td>${teamCell(fb,'games',0)}</td></tr></tbody></table></div>
<p class="note" style="margin-top:15px">Missing statistics stay absent. The seed model does not use form statistics. No injuries, rosters or market prices are modeled.</p>${season.model&&g.status!=='no_contest'?`<label for="detail-model">Compare probability model<select id="detail-model"><option value="seed">Seed baseline</option><option value="seed_curve">Seed curve challenger</option>${fa&&fb&&season.available_models?.includes('form')?'<option value="form">Pre-March form challenger</option>':''}</select></label><div id="detail-prediction" class="statusline" role="status"></div>`:''}`;
if(origin&&view==='actual'){const link=document.createElement('a');link.className='button';link.textContent='Compare saved forecasts →';link.href=`#matchup?${new URLSearchParams({compare_year:year,compare_game:g.id})}`;$('#detail-body').append(link);}
dialog.showModal();
const modelSelect=$('#detail-model'),prediction=$('#detail-prediction');
let predictionVersion=0;
modelSelect?.addEventListener('change',async()=>{
  const request=++predictionVersion,kind=modelSelect.value,label=modelSelect.selectedOptions[0].textContent;
  const isCurrent=()=>request===predictionVersion&&dialog.open&&modelSelect.isConnected&&prediction.isConnected;
  prediction.textContent=`Loading ${label.toLowerCase()} probability…`;
  prediction.setAttribute('aria-busy','true');
  try{
    const r=await api(`/api/predict?year=${year}&model=${kind}&a=${g.seed_a}&b=${g.seed_b}&team_a=${encodeURIComponent(g.a)}&team_b=${encodeURIComponent(g.b)}`);
    if(isCurrent())prediction.textContent=`${label} · ${labelTeam(g.a)} ${pct(r.p_a)} · ${labelTeam(g.b)} ${pct(r.p_b)} · trained through ${maxTrain(r.model)}`;
  }catch(err){
    if(isCurrent())prediction.textContent=`${label}: comparison unavailable. ${err.message}`;
  }finally{
    if(request===predictionVersion)prediction.removeAttribute('aria-busy');
  }
});
}
function matchup(params=new URLSearchParams()){main.innerHTML=heading('PROBABILITY EXPLORER','Matchup lab','Explore a seed scenario, then compare the saved forecasts for a recorded tournament game.')+
`<section class="panel"><form id="matchup-form"><div class="two-inputs"><label for="seed-a">Team A seed<input id="seed-a" name="a" type="number" min="1" max="16" step="1" value="5" required></label><label for="seed-b">Team B seed<input id="seed-b" name="b" type="number" min="1" max="16" step="1" value="12" required></label></div><div class="toolbar"><label for="matchup-model">Model<select id="matchup-model"><option value="seed">Seed baseline · primary</option><option value="seed_curve">Seed curve · challenger</option></select></label><button class="primary" type="submit">Compare seeds</button></div></form><div id="matchup-result" role="status"></div></section><div class="panels"><section class="panel"><h2>What a seed probability means</h2><p class="muted">Teams with the same seed receive the same probability. A 5 seed’s chance against a 12 seed reflects past seed outcomes, rather than this season’s roster or style of play.</p></section><section class="panel"><h2>Where the numbers come from</h2><p class="muted">Logistic regression on 2,582 played main-bracket games through 2026. A temperature adjustment uses prior rolling predictions. Swapping teams complements the probability exactly.</p><a href="#evidence">See the benchmark →</a></section></div>`;
const run=async()=>{const target=$('#matchup-result');target.textContent='Calculating…';try{const a=+$('#seed-a').value,b=+$('#seed-b').value;const r=await api(`/api/predict?a=${a}&b=${b}&model=${$('#matchup-model').value}&year=2027`);target.innerHTML=`<div class="comparison"><div><span class="muted">TEAM A · SEED ${a}</span><div class="probability">${pct(r.p_a)}</div></div><div class="right"><span class="muted">TEAM B · SEED ${b}</span><div class="probability">${pct(r.p_b)}</div></div></div><div class="prob-bar" aria-hidden="true"><span style="width:${r.p_a*100}%"></span></div><p class="note">Scenario probability · fitted through 2026 · no announced 2027 teams.</p><details><summary>Explain this probability</summary><p class="note">The model adds these feature contributions to log odds, then converts them to a probability. There is no intercept; equal seeds return 50%.</p><table><thead><tr><th>Feature</th><th class="numeric">Log-odds contribution</th></tr></thead><tbody>${r.contributions.map(c=>`<tr><td>${esc(c.feature)}</td><td class="numeric">${num(c.log_odds,3)}</td></tr>`).join('')}</tbody></table><p class="note">Temperature: ${num(r.model.temperature,3)} · training games: ${r.model.n_train}.</p></details>`;}catch(e){error(e,target);}};
$('#matchup-form').onsubmit=e=>{e.preventDefault();run();};run();
const comparison=document.createElement('section');comparison.id='matchup-comparison';comparison.className='panel season-insights matchup-compare';comparison.setAttribute('aria-labelledby','compare-title');$('.panels').before(comparison);mountMatchupComparison(comparison,{summary,request:api,initialYear:params.has('compare_year')?Number(params.get('compare_year')):year,initialGame:params.get('compare_game'),initialSide:params.get('compare_side')});
}
const names={coin:'50/50',seed_pick:'Fixed seed heuristic',seed:'Seed logistic · primary',seed_curve:'Seed curve challenger',form:'Pre-March form challenger'};
function metricTable(metrics){return `<div class="table-scroll"><table><caption class="sr-only">Probability model evaluation, lower Brier and log loss are better</caption><thead><tr><th>Forecaster</th><th class="numeric">Games</th><th class="numeric">Brier ↓</th><th class="numeric">Log loss ↓</th><th class="numeric">Accuracy</th><th class="numeric">ECE ↓</th></tr></thead><tbody>${Object.entries(metrics).map(([k,m])=>`<tr><td class="model-name">${names[k]}</td><td class="numeric">${m?.n??'—'}</td><td class="numeric">${num(m?.brier)}</td><td class="numeric">${num(m?.log_loss)}</td><td class="numeric">${pct(m?.accuracy)}</td><td class="numeric">${num(m?.ece)}</td></tr>`).join('')}</tbody></table></div>`;}
function calibrationChart(m){const points=m.calibration.filter(b=>b.count).map(b=>[40+b.predicted*380,230-b.observed*190]);return `<svg class="chart" viewBox="0 0 460 270" role="img" aria-label="Seed model reliability curve on the 2021 to 2026 holdout. The dashed diagonal is perfect calibration."><line class="grid" x1="40" y1="230" x2="420" y2="230"/><line class="grid" x1="40" y1="40" x2="40" y2="230"/><line class="reference" x1="40" y1="230" x2="420" y2="40"/><polyline class="curve" points="${points.map(p=>p.join(',')).join(' ')}"/>${points.map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="4"/>`).join('')}<text x="28" y="245">0</text><text x="411" y="245">1</text><text x="20" y="45">1</text><text x="125" y="263">Predicted probability</text><text x="45" y="26">Observed win fraction · seed model</text></svg>`;}
function evidence(inspectYear=year){const e=summary.evaluation;main.innerHTML=heading('THE HISTORICAL RECORD','Model evidence','Chronological retrospective evaluation · expanding training window · smaller Brier and log loss are better.')+
`<section class="panel season-insights" id="season-insights" aria-labelledby="season-insights-title"></section>
<section class="panel"><h2>2021–2026 holdout</h2>${metricTable(e.holdout_metrics)}<p class="note" style="margin-top:16px">Form coverage may differ; use the paired table below for comparison. One 2021 no-contest is excluded. This holdout was inspected during initial development and is not a prospective track record.</p></section>
<div class="panels"><section class="panel"><h2>Calibration · primary seed model</h2>${calibrationChart(e.holdout_metrics.seed)}<p class="note">Ten equal-width probability bins, mirrored opponent orientation. Effective sample remains 377 games. The diagonal marks agreement between probability and observed frequency. ECE: ${num(e.holdout_metrics.seed.ece)}.</p></section><section class="panel"><h2>What the evidence supports</h2><p class="muted">The seed logistic model improves Brier and log loss over the fixed seed heuristic in this holdout. The curve and form models remain visible challengers. The primary is kept simple until stronger evidence supports a change.</p><p class="note">No market benchmark, prospective score or certainty interval is available. A few tournaments can shift the result. More old games do not guarantee better 2027 predictions.</p><a href="#about">Read the information horizon →</a></section></div>
<details><summary>Paired comparison · form-feature games only</summary>${metricTable(e.paired_form_holdout)}<p class="note">Compare models on identical game IDs. Form statistics use only results before March 1; seeds are selection-time information. No selection-day form claim is made.</p></details>
<details><summary>Paired Brier uncertainty · holdout tournaments</summary><div class="table-scroll"><table><thead><tr><th>Comparison</th><th class="numeric">Brier gap</th><th class="numeric">95% interval</th></tr></thead><tbody>${e.paired_uncertainty.filter(Boolean).map(r=>`<tr><td>${names[r.challenger]} vs ${names[r.baseline]}</td><td class="numeric">${num(r.brier_gap,5)}</td><td class="numeric">[${num(r.interval95[0],5)}, ${num(r.interval95[1],5)}]</td></tr>`).join('')}</tbody></table></div><p class="note">5,000 bootstrap samples clustered by tournament. Negative gaps favor the first model. Only six holdout tournaments: these intervals are unstable and do not establish future superiority.</p></details>
<details><summary>Development years · 1995–2019</summary>${metricTable(e.development_metrics)}</details>
<details><summary>Holdout by tournament</summary><div class="table-scroll"><table><thead><tr><th>Year</th><th class="numeric">Games</th><th class="numeric">Seed Brier</th><th class="numeric">Curve Brier</th><th class="numeric">Form Brier</th></tr></thead><tbody>${[2021,2022,2023,2024,2025,2026].map(y=>`<tr><td>${y}</td><td class="numeric">${e.by_season[y].seed.n}</td><td class="numeric">${num(e.by_season[y].seed.brier)}</td><td class="numeric">${num(e.by_season[y].seed_curve.brier)}</td><td class="numeric">${num(e.by_season[y].form?.brier)}</td></tr>`).join('')}</tbody></table></div></details>
<details><summary>Calibration bins · primary model</summary><div class="table-scroll"><table><thead><tr><th>Bin</th><th class="numeric">Mirrored observations</th><th class="numeric">Prediction</th><th class="numeric">Observed</th></tr></thead><tbody>${e.holdout_metrics.seed.calibration.map(b=>`<tr><td>${b.lower.toFixed(1)}–${(b.lower+.1).toFixed(1)}</td><td class="numeric">${b.count}</td><td class="numeric">${pct(b.predicted)}</td><td class="numeric">${pct(b.observed)}</td></tr>`).join('')}</tbody></table></div></details>`;
mountSeasonInsights($('#season-insights'),{summary,request:api,initialYear:inspectYear,onOpenArchive:selected=>{year=selected;region=0;simulation=null;view='actual';}});}
function about(){main.innerHTML=heading('PROVENANCE & LIMITS','Know the data','Archive coverage, feature coverage and future tournament structure are different facts.')+
`<section class="panel"><h2>Historical main-bracket archive</h2><p>41 tournaments from 1985–2026, excluding cancelled 2020. Each source file contains 64 bracket-ordered teams, seeds and main-bracket win totals. Matchups and advancements are reconstructed and validated. ${summary.provenance.score_date_enrichment?.results_with_scores??0} modern results have been independently matched to SportsDataverse/ESPN for scores and UTC dates.</p><p class="note"><a href="https://github.com/possibly-wrong/ncaa-tournament">possibly-wrong/ncaa-tournament</a> · Unlicense · pinned commit <code>${summary.provenance.commit}</code> · retrieved October 3, 2026. Community maintained; not an official NCAA feed.</p><ul class="list"><li>1939–1984: not ingested.</li><li>Opening/First Four games and preliminary-round losers: not covered.</li><li>Scores/dates before 2006, venues and geographic region names: unavailable.</li><li>Oregon–VCU 2021: no-contest advancement, excluded from fitting and scoring.</li></ul></section>
<div class="panels"><section class="panel"><h2>Modern schedule features</h2><p class="muted">SportsDataverse schedules, upstream ESPN, are used to derive within-season Elo, win rate and mean scoring margin. Features freeze at March 1, 00:00 UTC. Team matches use exact names and reviewed aliases; missing mappings stay absent.</p><p class="note"><a href="https://github.com/sportsdataverse/hoopR-mbb-data">SportsDataverse hoopR-mbb-data authors</a> · <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. Derived statistics are adaptations. Retrieved retrospectively; source corrections may postdate games. No completeness claim for all NCAA regular-season games.</p></section><section class="panel"><h2>How probabilities are trained</h2><p class="muted">Ridge logistic regression with fixed feature scales and no intercept. Annual evaluation refits on strictly earlier tournaments. Temperature calibration uses earlier out-of-fold predictions. The curve challenger adds a log-seed ratio; the form challenger adds pre-March team form.</p><p class="note">Outcome labels and tournament win totals never enter features. Seeds already summarize selection information. Same-seed teams remain equal under the primary model.</p></section></div>
<section class="panel"><h2>Tournament structure changes</h2><p class="muted">The tournament began in 1939. The 64-team era began in 1985, an opening game expanded the field to 65 in 2001, and the First Four expanded it to 68 in 2011. The 2020 event was cancelled. For 2027, the published format has 76 teams and 12 Opening Round games feeding the 64-team bracket.</p><p class="note">The simulator reads declared slots and pairs. Historical 64-team experiments are conditional on preliminary-round survivors, so their odds should not be described as selection-day full-field forecasts.</p><p><a href="https://www.ncaa.com/news/basketball-men/article/2020-06-04/march-madness-history-and-origins">NCAA tournament history</a> · <a href="${esc(summary.field.source)}">2027 NCAA schedule</a></p></section>
<section class="panel" style="margin-top:24px"><h2>Practical limits</h2><p class="muted">These models omit injuries, rosters, transfers, matchup style and market prices. Bracket odds integrate possible paths while treating fitted game probabilities as fixed. They do not include parameter uncertainty or forecast a team’s chance of qualifying for the tournament.</p><p class="note">Kaggle is optional and not ingested. No login, paid API, new data agreement or deployment is required to run this local version. Model artifacts and source coverage can be regenerated with the documented CLI.</p></section>`;}
async function renderRoute(){const version=++routeVersion,[routeName,query='']=location.hash.slice(1).split('?'),route=routeName||'2027',params=new URLSearchParams(query);if(dialog.open)dialog.close();document.querySelectorAll('nav a').forEach(a=>{const active=a.hash===`#${route==='team'?'archive':route}`;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.title=`${{archive:'Historical bracket',team:'Team tournament history',matchup:'Matchup lab',evidence:'Model evidence',about:'Data & method'}[route]||'2027 tournament'} · March Lab`;try{if(!summary)summary=await api('/api/summary');if(version!==routeVersion)return;
const validYear=(value,fallback)=>summary.years.includes(Number(value))?Number(value):fallback,validRegion=value=>/^[0-4]$/.test(value??'')?Number(value):0;
if(route==='archive'){year=validYear(params.get('year'),year);simulation=simulations.get(year)||null;if(params.has('region'))region=validRegion(params.get('region'));view=params.get('view')==='sample'&&simulation?'sample':'actual';syncArchiveRoute(params.get('game'));await archive({focusGame:params.get('game')});}
else if(route==='team'){const origin={year:validYear(params.get('from'),year),region:validRegion(params.get('from_region')),game:params.get('from_game'),view:params.get('from_view')==='sample'?'sample':'actual'},requested=Number(params.get('appearance')),appearanceYear=Number.isInteger(requested)&&requested>=1939&&requested<=2100?requested:origin.year;await renderTeamProfile(main,{profileId:params.get('profile')||'',request:api,origin,appearanceYear,scoutWindow:params.get('scout_window'),isCurrent:()=>version===routeVersion});if(version===routeVersion)main.focus({preventScroll:true});}
else if(route==='matchup')matchup(params);else if(route==='evidence'){const inspected=Number(params.get('year'));evidence([...summary.years,...summary.provenance.cancelled_years].includes(inspected)?inspected:year);}else if(route==='about')about();else upcoming();}catch(e){if(version===routeVersion)error(e);}}
$('#close-detail').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
window.addEventListener('hashchange',renderRoute);renderRoute();
